### ISSUE TITLE
Scrape more than first page

### ISSUE THREAD

**Issue by jepperaskdk** [scrapehero/yellowpages-scraper#6]
Currently it only returns the first 30 hits. You can add a page attribute to get the results from a specific page, like this:

`url = "https://www.yellowpages.com/search?search_terms={0}&geo_location_terms={1}&page={2}".format(keyword, place, page_count)`

You can then do this in a while-loop, incrementing page_count and breaking when `len(listings) == 0`. This requires storing the results outside the loop and returning them after the loop.
In addition, phone-numbers, street and more doesn't seem to work, the xpath-queries should be like this:
```
XPATH_TELEPHONE = ".//div[@class='info']//div[contains(@class,'info-section info-secondary')]//div[contains(@class, 'phone')]//text()"
XPATH_STREET = ".//div[@class='info']//div[contains(@class,'info-section info-secondary')]//div[contains(@class, 'street-address')]//text()"
XPATH_LOCALITY = ".//div[@class='info']//div[contains(@class,'info-section info-secondary')]//div[contains(@class, 'locality')]//text()"
```

**Comment by Dwoelper** [comment]
any info on grabbing the email?

can you share code you are using to get info off of all available pages

**Comment by jepperaskdk** [comment]
> any info on grabbing the email?
> 
> can you share code you are using to get info off of all available pages

AFAIK e-mail is only available if you click on one of the listings, so it would require doing an additional request and then pulling out the email. You could do it like this:

```
def get_email(url):
    headers = {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
               'Accept-Encoding': 'gzip, deflate, br',
               'Accept-Language': 'en-GB,en;q=0.9,en-US;q=0.8,ml;q=0.7',
               'Cache-Control': 'max-age=0',
               'Connection': 'keep-alive',
               'Host': 'www.yellowpages.com',
               'Upgrade-Insecure-Requests': '1',
               'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36'
               }
    response = requests.get(url, verify=False, headers=headers)
    if response.status_code == 200:
        parser = html.fromstring(response.text)
        base_url = "https://www.yellowpages.com"
        parser.make_links_absolute(base_url)
        try:
            result = parser.xpath(".//a[contains(@class, 'email-business')]//@href")[0].replace("mailto:", "")
        except Exception as e:
            result = "N/A"

        return result
```
And then call this function from inside the listings-loop:
```raw_email = get_email(raw_business_page[0])```

It will be a lot slower of course, due to the extra requests.

**Comment by Dwoelper** [comment]
Where abouts would i place this code in the original code?

**Comment by jepperaskdk** [comment]
> Where abouts would i place this code in the original code?

Put the function here: https://github.com/scrapehero/yellowpages-scraper/blob/28558819e1c7ce9a9e82b004e38859027558e046/yellow_pages.py#L8

Put the function-call here: https://github.com/scrapehero/yellowpages-scraper/blob/28558819e1c7ce9a9e82b004e38859027558e046/yellow_pages.py#L70

**Comment by Dwoelper** [comment]
That worked! thank you! what about looping to search multiple pages?

**Comment by Dwoelper** [comment]
also want to run this through a proxy. https://www.us-proxy.org/

**Comment by Dwoelper** [comment]
@jepperaskdk stuck on the loop to get past first page. any thoughts?

**Comment by jepperaskdk** [comment]
You should be able to figure it out from what I've written above.
I won't provide further answers, as I just realized scraping is actually against YP's terms of conditions (§2.1): https://www.yellowpages.com/about/legal/terms-conditions
